name: quiz_prokit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Base
  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.3
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0

  # State Management
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # Quiz
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.3
  lazy_data_table: ^0.3.1
  syncfusion_flutter_datagrid: ^23.1.36
  booking_calendar: ^1.1.9
  flutter_neat_and_clean_calendar:
  table_calendar:
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0
  device_info_plus: ^9.0.3
  ussd_advanced: ^1.1.0

  sim_data: ^0.0.2
  flutter_sms_inbox: ^1.0.3
  flutter_local_notifications: ^16.0.0+1
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.0.1
  shared_preferences: ^2.2.1

  signalr_netcore:
    git:
      url: https://github.com/geekz-reno/signalr_client.git
      ref: master
  permission_handler: ^11.0.1
  connectivity_plus: ^4.0.2
  type_plus: ^2.0.1
  dot_cast: ^1.2.0
  fluttertoast: ^8.2.2
  rive: ^0.11.17
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  expansion_tile_card: ^3.0.0
  flutter_fast_forms: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/etudicon.png"




flutter:
  uses-material-design: true

  assets:
  - images/quiz/
  - images/
  - assets/animation/
  - assets/image/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
